name: TestEnv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
        
    - name: Build with Gradle
      run: ./gradlew assembleRelease
      
    - name: Decode Keystore
      run: echo ${{ secrets.KEYSTORE_FILE }} | base64 --decode > keystore.jks
      
    - name: Sign APK with apksigner
      run: |
        $ANDROID_HOME/build-tools/31.0.0/apksigner sign \
          --ks keystore.jks \
          --ks-key-alias ${{ secrets.KEY_ALIAS }} \
          --ks-pass env:KEYSTORE_PASSWORD \
          codec2talkie/build/outputs/apk/release/codec2talkie-release-unsigned.apk \
          --out codec2talkie/build/outputs/apk/release/codec2talkie-release.apk 
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
                  
    - name: Verify APK
      run: $ANDROID_HOME/build-tools/31.0.0/apksigner verify codec2talkie/build/outputs/apk/release/codec2talkie-release.apk
        
    - name: Upload signed APK
      uses: actions/upload-artifact@v4
      with:
        name: codec2talkie-release.apk
        path: codec2talkie/build/outputs/apk/release/codec2talkie-release.apk
